#!/bin/sh
# Escape HTML characters from all src/ files
# $Id: escape,v 1.1 2002/07/02 07:43:38 zhware Exp $

SRC=`find ../src/ -type f -maxdepth 1`
ESC_DIR=../src_esc
ESCAPER=../tools/src_esc

if [ ! -d $ESC_DIR ]; then
   mkdir $ESC_DIR
fi

for src in $SRC; do
   $ESCAPER $src > $ESC_DIR/`basename $src`.esc
done
