#!/bin/sh
# Escape special HTML characters
# $Id: src_esc,v 1.1 2002/07/02 07:43:38 zhware Exp $

sed -e 's/&/\&amp;/g'	\
    -e 's/</\&lt;/g'	\
    -e 's/>/\&gt;/g'	\
    -e 's/ä/\&auml;/g'	\
    -e 's/ö/\&ouml;/g'	\
    -e 's/ü/\&uuml;/g'	\
    -e 's/ß/\&szlig;/g'	\
    -e 's/Ä/\&Auml;/g'	\
    -e 's/Ö/\&Ouml;/g'	\
    -e 's/Ü/\&Uuml;/g'	\
	"$@"
